apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
        - name: frontend
          image: brianbwire/brian-yolo-frontend:v1.0.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend-service
spec:
  selector:
    app: yolo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
