---
- name: Build frontend Docker image
  docker_image:
    name: yolo-frontend
    build:
      path: /home/vagrant/yolo/client
    source: build

- name: Run frontend container
  docker_container:
    name: yolo-frontend
    image: yolo-frontend
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    env:
      REACT_APP_BACKEND_URL: "http://192.168.56.10:5000"
